services:
  ros2:
    image: ghcr.io/ros2gorobotics/ros2-course-jazzy-rviz:latest
    container_name: ros2_jazzy_rviz

    stdin_open: true
    tty: true

    environment:
      QT_X11_NO_MITSHM: "1"

    volumes:
      - ./workspace:/home/student/ros2_ws

    restart: unless-stopped
