services:
  ros2:
    image: ghcr.io/ros2gorobotics/ros2-course-jazzy-rviz:latest
    container_name: ros2_jazzy_rviz

    stdin_open: true
    tty: true

    environment:
      DISPLAY: ":0"
      WAYLAND_DISPLAY: "wayland-0"
      XDG_RUNTIME_DIR: "/run/user/1000"
      QT_QPA_PLATFORM: "xcb"
      QT_X11_NO_MITSHM: "1"

    volumes:
      - ros2_course_workspace:/home/student/ros2_ws
      - /mnt/wslg:/mnt/wslg
      - /mnt/wslg/.X11-unix:/tmp/.X11-unix

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

    restart: unless-stopped

volumes:
  ros2_course_workspace:
